### ISSUE TITLE
babel-polyfill 6.3.24 support

### ISSUE THREAD

**Issue by jvmlet** [webjars/babel#3]
Please add 6.3.24 jar.
Also, current  6.0.16  has broken dependencies :

```
Could not find org.webjars.npm:recast:0.10.25.
   Required by:
     rootPrj> org.webjars.npm:babel-polyfill:6.0.16 > org.webjars.npm:regenerator:0.8.36 > org.webjars.npm:commoner:0.10.1
```

Thanks

**Comment by jamesward** [comment]
Are you using the NPM WebJar or the Classic WebJar?  For some reason `6.3.24` doesn't exist in NPM: https://registry.npmjs.org/babel-core

I'm releasing `6.3.26` of this Classic WebJar instead but I'm not sure if that is what you need.

**Comment by jvmlet** [comment]
I see all babel releases got new version 6.3.26 at http://www.webjars.org/ except <b>babel-polyfill</b> which is 6.0.16.
The latest is https://registry.npmjs.org/babel-polyfill/6.3.14
I'm using Classic WebJar.
Thanks

**Comment by jamesward** [comment]
`babel-polyfill` is an NPM WebJar and you can release new versions yourself: http://www.webjars.org/npm
